version: "2"

services:

  redis:
    image: redis:3.2.11
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.0
    ports:
      - "9200:9200"
    # volumes:
    #   - ./esdata/:/usr/share/elasticsearch/data/

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.0
    ports:
      - "5601:5601"
    # environment:
    #   - ELASTICSEARCH_URL=http://elasticsearch:9200
